apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-pulse.fullname" . }}-config
  labels:
    {{- include "infra-pulse.labels" . | nindent 4 }}
data:
  APPLICATION_ENV: "production"
  LOGGING_LEVEL_ROOT: "INFO"
